$kind: http-request
url: "{{baseUrl}}/api/accounts"
method: GET
headers:
  Authorization: Bearer {{userToken}}AA
scripts:
  - type: afterResponse
    code: pm.test('401 invalid signature', () => pm.response.to.have.status(401));
    language: text/javascript
order: 2000
