$kind: http-request
url: "{{baseUrl}}/api/admin/users/1"
method: PATCH
headers:
  Authorization: Bearer {{userToken}}
  Content-Type: application/json
body:
  type: text
  content: |-
    {
      "is_active": 0
    }
scripts:
  - type: afterResponse
    code: pm.test('403', () => pm.response.to.have.status(403));
    language: text/javascript
order: 5000
