const banksByCountry = {
  US: [
    { name: 'JPMorgan Chase', swift: 'CHASUS33' },
    { name: 'Bank of America', swift: 'BOFAUS3N' },
    { name: 'Wells Fargo', swift: 'WFBIUS6S' },
    { name: 'Citibank', swift: 'CITIUS33' },
    { name: 'U.S. Bank', swift: 'USBKUS44' },
    { name: 'PNC Bank', swift: 'PNCCUS33' },
    { name: 'Truist Bank', swift: 'BRBTUS33' },
  ],
  CA: [
    { name: 'Royal Bank of Canada', swift: 'ROYCCAT2' },
    { name: 'TD Canada Trust', swift: 'TDOMCATTTOR' },
    { name: 'Scotiabank', swift: 'NOSCCATT' },
    { name: 'Bank of Montreal', swift: 'BOFMCAM2' },
    { name: 'CIBC', swift: 'CIBCCATT' },
    { name: 'National Bank of Canada', swift: 'BNDCCAMMINT' },
  ],
  GB: [
    { name: 'Barclays', swift: 'BARCGB22' },
    { name: 'HSBC UK', swift: 'HBUKGB4B' },
    { name: 'Lloyds Bank', swift: 'LOYDGB2L' },
    { name: 'NatWest', swift: 'NWBKGB2L' },
    { name: 'Santander UK', swift: 'ABBYGB2L' },
    { name: 'Standard Chartered', swift: 'SCBLGB2L' },
    { name: 'Monzo Bank', swift: 'MONZGB2L' },
  ],
  DE: [
    { name: 'Deutsche Bank', swift: 'DEUTDEFF' },
    { name: 'Commerzbank', swift: 'COBADEFF' },
    { name: 'DZ Bank', swift: 'GENODEFF' },
    { name: 'KfW Bankengruppe', swift: 'KFWIDEFF' },
    { name: 'Sparkasse', swift: 'HASPDEHH' },
    { name: 'N26', swift: 'NTSBDEB1' },
  ],
  FR: [
    { name: 'BNP Paribas', swift: 'BNPAFRPP' },
    { name: 'Credit Agricole', swift: 'AGRIFRPP' },
    { name: 'Societe Generale', swift: 'SOGEFRPP' },
    { name: 'Credit Mutuel', swift: 'CMCIFRPP' },
    { name: 'La Banque Postale', swift: 'PSSTFRPP' },
    { name: 'BPCE', swift: 'BPCEFRPP' },
  ],
  NL: [
    { name: 'ING Bank', swift: 'INGBNL2A' },
    { name: 'ABN AMRO', swift: 'ABNANL2A' },
    { name: 'Rabobank', swift: 'RABONL2U' },
    { name: 'SNS Bank', swift: 'SNSBNL2A' },
    { name: 'Triodos Bank', swift: 'TRIONL2U' },
    { name: 'bunq', swift: 'BUNQNL2A' },
  ],
  ES: [
    { name: 'Banco Santander', swift: 'BSCHESMM' },
    { name: 'BBVA', swift: 'BBVAESMM' },
    { name: 'CaixaBank', swift: 'CAIXESBB' },
    { name: 'Banco Sabadell', swift: 'BSABESBB' },
    { name: 'Bankinter', swift: 'BKBKESMM' },
    { name: 'ING Espana', swift: 'INGDESMM' },
  ],
  IT: [
    { name: 'Intesa Sanpaolo', swift: 'BCITITMM' },
    { name: 'UniCredit', swift: 'UNCRITMM' },
    { name: 'Banco BPM', swift: 'BAPPIT21' },
    { name: 'BPER Banca', swift: 'BPMOIT22' },
    { name: 'Mediobanca', swift: 'MEDBITMM' },
    { name: 'Poste Italiane', swift: 'BPPIITRR' },
  ],
  PT: [
    { name: 'Caixa Geral de Depositos', swift: 'CGDIPTPL' },
    { name: 'Millennium BCP', swift: 'BCOMPTPL' },
    { name: 'Banco Santander Totta', swift: 'TOTAPTPL' },
    { name: 'Novo Banco', swift: 'BESCPTPL' },
    { name: 'Banco BPI', swift: 'BBPIPTPL' },
  ],
  BE: [
    { name: 'KBC Bank', swift: 'KREDBEBB' },
    { name: 'BNP Paribas Fortis', swift: 'GEBABEBB' },
    { name: 'Belfius Bank', swift: 'GKCCBEBB' },
    { name: 'ING Belgium', swift: 'BBRUBEBB' },
    { name: 'Argenta', swift: 'ARSPBE22' },
  ],
  IE: [
    { name: 'Bank of Ireland', swift: 'BOFIIE2D' },
    { name: 'AIB', swift: 'AIBKIE2D' },
    { name: 'Permanent TSB', swift: 'IPBSIE2D' },
    { name: 'Ulster Bank Ireland', swift: 'ULSBIE2D' },
    { name: 'Revolut Bank', swift: 'REVOIE23' },
  ],
  CH: [
    { name: 'UBS', swift: 'UBSWCHZH80A' },
    { name: 'Credit Suisse', swift: 'CRESCHZZ80A' },
    { name: 'Raiffeisen Switzerland', swift: 'RAIFCH22' },
    { name: 'PostFinance', swift: 'POFICHBE' },
    { name: 'Zurich Cantonal Bank', swift: 'ZKBKCHZZ80A' },
    { name: 'Julius Baer', swift: 'BAERCHZZ' },
  ],
  SE: [
    { name: 'Swedbank', swift: 'SWEDSESS' },
    { name: 'SEB', swift: 'ESSESESS' },
    { name: 'Handelsbanken', swift: 'HANDSESS' },
    { name: 'Nordea Sweden', swift: 'NDEASESS' },
    { name: 'Lansforsakringar', swift: 'ELLFSESS' },
  ],
  NO: [
    { name: 'DNB', swift: 'DNBANOKK' },
    { name: 'Nordea Norway', swift: 'NDEANOKK' },
    { name: 'SpareBank 1', swift: 'SPRONO22' },
    { name: 'Handelsbanken Norge', swift: 'HANDNOKK' },
    { name: 'Storebrand Bank', swift: 'STBKNOKK' },
  ],
  DK: [
    { name: 'Danske Bank', swift: 'DABADKKK' },
    { name: 'Nordea Denmark', swift: 'NDEADKKK' },
    { name: 'Jyske Bank', swift: 'JYBADKKK' },
    { name: 'Sydbank', swift: 'SYBKDK22' },
    { name: 'Spar Nord Bank', swift: 'SPNODK22' },
  ],
  PL: [
    { name: 'PKO Bank Polski', swift: 'BPKOPLPW' },
    { name: 'Bank Pekao', swift: 'PKOPPLPW' },
    { name: 'Santander Bank Polska', swift: 'WBKPPLPP' },
    { name: 'mBank', swift: 'BREXPLPW' },
    { name: 'ING Bank Slaski', swift: 'INGBPLPW' },
    { name: 'Millennium Bank', swift: 'BIGBPLPW' },
  ],
  NG: [
    { name: 'Guaranty Trust Bank', swift: 'GTBINGLA' },
    { name: 'Zenith Bank', swift: 'ZEIBNGLA' },
    { name: 'Access Bank', swift: 'ABNGNGLA' },
    { name: 'United Bank for Africa', swift: 'UNAFNGLA' },
    { name: 'First Bank of Nigeria', swift: 'FBNINGLA' },
    { name: 'Stanbic IBTC Bank', swift: 'SBICNGLX' },
    { name: 'Fidelity Bank', swift: 'FIDTNGLA' },
    { name: 'Opay', swift: 'OPAYNGLA' },
  ],
  KE: [
    { name: 'Equity Bank', swift: 'EQBLKENA' },
    { name: 'KCB Bank', swift: 'KCBLKENX' },
    { name: 'Co-operative Bank', swift: 'KCOOKENA' },
    { name: 'Standard Chartered Kenya', swift: 'SCBLKENX' },
    { name: 'Absa Bank Kenya', swift: 'BARCKENX' },
    { name: 'NCBA Bank', swift: 'CBAFKENX' },
  ],
  ZA: [
    { name: 'Standard Bank', swift: 'SBZAZAJJ' },
    { name: 'FirstRand Bank (FNB)', swift: 'FIRNZAJJ' },
    { name: 'Absa Bank', swift: 'ABSAZAJJ' },
    { name: 'Nedbank', swift: 'NEDSZAJJ' },
    { name: 'Capitec Bank', swift: 'CABLZAJJ' },
    { name: 'Investec Bank', swift: 'IVESZAJJ' },
  ],
  GH: [
    { name: 'GCB Bank', swift: 'GHCBGHAC' },
    { name: 'Ecobank Ghana', swift: 'ECOCGHAC' },
    { name: 'Standard Chartered Ghana', swift: 'SCBLGHAC' },
    { name: 'Absa Bank Ghana', swift: 'BARCGHAC' },
    { name: 'Fidelity Bank Ghana', swift: 'FBLIGHAC' },
    { name: 'Zenith Bank Ghana', swift: 'ZEPLGHAC' },
  ],
  EG: [
    { name: 'National Bank of Egypt', swift: 'NBEGEGCX' },
    { name: 'Banque Misr', swift: 'BMISEGCX' },
    { name: 'Commercial International Bank', swift: 'CIBEEGCX' },
    { name: 'QNB Alahli', swift: 'QNBAEGCX' },
    { name: 'HSBC Egypt', swift: 'EBBKEGCX' },
    { name: 'Bank of Alexandria', swift: 'ALEXEGCX' },
  ],
  TZ: [
    { name: 'CRDB Bank', swift: 'CORUTZTZ' },
    { name: 'NMB Bank', swift: 'NMIBTZTZ' },
    { name: 'NBC Tanzania', swift: 'NLCBTZTX' },
    { name: 'Stanbic Bank Tanzania', swift: 'SBICTZTX' },
    { name: 'Exim Bank Tanzania', swift: 'EXTNTZTZ' },
  ],
  ET: [
    { name: 'Commercial Bank of Ethiopia', swift: 'CBETETAA' },
    { name: 'Awash Bank', swift: 'AWINETAA' },
    { name: 'Dashen Bank', swift: 'DASHETAA' },
    { name: 'Bank of Abyssinia', swift: 'ABYSETAA' },
    { name: 'Wegagen Bank', swift: 'WEGAETAA' },
  ],
  RW: [
    { name: 'Bank of Kigali', swift: 'BKIGRWRW' },
    { name: 'I&M Bank Rwanda', swift: 'BCRORWRW' },
    { name: 'Equity Bank Rwanda', swift: 'EQBLRWRW' },
    { name: 'Cogebanque', swift: 'CGBKRWRW' },
    { name: 'Access Bank Rwanda', swift: 'AFRIRWRW' },
  ],
  UG: [
    { name: 'Stanbic Bank Uganda', swift: 'SBICUGKX' },
    { name: 'Centenary Bank', swift: 'CERBUGKA' },
    { name: 'Standard Chartered Uganda', swift: 'SCBLUGKA' },
    { name: 'Absa Bank Uganda', swift: 'BARCUGKX' },
    { name: 'DFCU Bank', swift: 'DFCUUGKA' },
  ],
  CM: [
    { name: 'Afriland First Bank', swift: 'CCEICMCX' },
    { name: 'Societe Generale Cameroun', swift: 'SGCMCMCX' },
    { name: 'Ecobank Cameroon', swift: 'ECOCCMCX' },
    { name: 'Commercial Bank of Cameroon', swift: 'BICECMCX' },
    { name: 'United Bank for Africa Cameroon', swift: 'UNAFCMCX' },
  ],
  SN: [
    { name: 'CBAO Senegal', swift: 'CBAOSNDA' },
    { name: 'Ecobank Senegal', swift: 'ECOCSNDA' },
    { name: 'Societe Generale Senegal', swift: 'SGSNSNDA' },
    { name: 'Banque Atlantique Senegal', swift: 'ATSNSNDA' },
    { name: 'UBA Senegal', swift: 'UNAFSNDX' },
  ],
  MA: [
    { name: 'Attijariwafa Bank', swift: 'BCMAMAMC' },
    { name: 'Banque Populaire du Maroc', swift: 'BCPOMAMC' },
    { name: 'BMCE Bank of Africa', swift: 'BMCEMAMC' },
    { name: 'Credit du Maroc', swift: 'CDMAMAMC' },
    { name: 'CIH Bank', swift: 'CIHMMAMC' },
  ],
};

function getBanksForCountry(countryCode) {
  return banksByCountry[countryCode] || [];
}

module.exports = { banksByCountry, getBanksForCountry };
